- 통계분석방법 3주차 실습
- 작성자 : 컴퓨터공학과 12201830 김건탁

In [ ]:
import numpy as np # numpy 라이브러리 import

In [ ]:
# 1
# rand 는 0부터 1 사이의 균일 분포에서 난수 matrix arrray 생성
# np.random.rand(2, 5) => 2x5 의 표준 정규분포 난수를 생성한다.
rand_1 = np.random.rand(10)
print(rand_1)

# randint는 균일 분포의 정수 난수 1개를 생성한다
# randn은 가우시안 표준 정규 분포에서 난수 matrix array를 생성한다.

[0.24812074 0.60292926 0.12502298 0.58031298 0.60752473 0.47652325
 0.10031915 0.95811186 0.20754503 0.38614066]


In [ ]:
# 2
rand_2 = np.random.randint(1, 1000, (2, 5)) # 1~999 사이의 난수를 2x5 행렬 형태로 생성
print(rand_2)

[[335 111 192 911 964]
 [486 594   4 812 702]]


In [ ]:
# 2-1
print("Total Sum :", rand_2.sum())
print("Column Sum : ", rand_2.sum(axis=0))
print("Row Sum : ", rand_2.sum(axis=1))

Total Sum : 5111
Column Sum :  [ 821  705  196 1723 1666]
Row Sum :  [2513 2598]


In [ ]:
# 2-2
print("Total Mean :", rand_2.mean())
print("Column Mean : ", rand_2.mean(axis=0))
print("Row Mean : ", rand_2.mean(axis=1))

Total Mean : 511.1
Column Mean :  [410.5 352.5  98.  861.5 833. ]
Row Mean :  [502.6 519.6]


In [ ]:
# 3
rand_5 = np.random.normal(loc=5, scale=1, size=5)
rand_10 = np.random.normal(loc=5, scale=1, size=10)
rand_100 = np.random.normal(loc=5, scale=1, size=100)
rand_1000 = np.random.normal(loc=5, scale=1, size=1000)

In [ ]:
# 3-1
print(f"5개 평균 - 5 = {rand_5.mean() - 5}")
print(f"10개 평균 - 5 = {rand_10.mean() - 5}")
print(f"100개 평균 - 5 = {rand_100.mean() - 5}")
print(f"1000개 평균 - 5 = {rand_1000.mean() - 5}")

5개 평균 - 5 = 0.6451525908550568
10개 평균 - 5 = 0.28863641148774466
100개 평균 - 5 = -0.0032152879446902816
1000개 평균 - 5 = 0.07789771841019011


In [ ]:
# 3-2
print(f"5개 표준편차 - 1 = {rand_5.std() - 1}")
print(f"10개 표준편차 - 1 = {rand_10.std() - 1}")
print(f"100개 표준편차 - 1 = {rand_100.std() - 1}")
print(f"1000개 표준편차 - 1 = {rand_1000.std() - 1}")

5개 표준편차 - 1 = -0.30774605950622125
10개 표준편차 - 1 = -0.1470029698084061
100개 표준편차 - 1 = 0.07199559393238775
1000개 표준편차 - 1 = -0.021155577826070027


In [ ]:
# 4
import time # 시간을 측정하기 위한 라이브러리

N = 300
rmatrix_a = np.array(np.random.rand(N, N))
rmatrix_b = np.array(np.random.rand(N, N))
matrix_z = np.zeros((N, N))

In [ ]:
# 4-1
start = time.time()

for i in range(N):
  for j in range(N):
    for t in range(N):
      matrix_z[i][j] += rmatrix_a[i][t] * rmatrix_b[t][i]

print("걸린 시간 : %.2f" % float(time.time() - start))

걸린 시간 : 30.38


In [ ]:
# 4-2 numpy 사용
start = time.time()
matrix_z = np.dot(rmatrix_a, rmatrix_b)

print("걸린 시간 : %.2f" % float(time.time() - start))

걸린 시간 : 0.01


In [ ]:
# 5
arr = np.arange(0, 10, 1)
lin = np.linspace(0, 10, 11)

In [ ]:
# 5-1
print(arr)
print(lin)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 6
print(np.eye(3, 3, 1))
print(np.eye(3, 3, -1))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
# 7
# numpy.diag 에 1차원 벡터를 인자로 입력하면, 해당 벡터를 대각행렬로 가지는 2nd matrix 생성
diag = np.arange(0, 20, 5)
np.diag(diag)

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
# 8
A = np.arange(1, 5, 1).reshape(2, -1)
B = np.arange(5, 9, 1).reshape(2, -1)

print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# 8-1
print("dot 결과")
print(np.dot(A, B))
print("\n\ninner 결과")
print(np.inner(A, B))

dot 결과
[[19 22]
 [43 50]]


inner 결과
[[17 23]
 [39 53]]


In [ ]:
# 8-2
print("A.dot(B)")
print(A.dot(B))

print("np.dot(A, B)")
print(np.dot(A, B))

print("np.mat(A) * np.mat(B)")
print(np.mat(A) * np.mat(B))

print("np.matmul(A, B)")
print(np.matmul(A, B))

A.dot(B)
[[19 22]
 [43 50]]
np.dot(A, B)
[[19 22]
 [43 50]]
np.mat(A) * np.mat(B)
[[19 22]
 [43 50]]
np.matmul(A, B)
[[19 22]
 [43 50]]


In [ ]:
# 9
matrix_3x3 = np.arange(3*3).reshape(3, -1)
matrix_3x4 = np.arange(3*4).reshape(3, -1)

print(matrix_3x3)
print(matrix_3x4)

print("\n\n곱 연산")
print(np.matmul(matrix_3x3, matrix_3x4))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


곱 연산
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]]


In [ ]:
# 10
tran = np.arange(3*4).reshape(3, -1)
print("전치 전", tran)
print("전치 후", np.transpose(tran))

전치 전 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
전치 후 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# 11
import numpy.linalg as la

In [ ]:
C = np.array([[6, 2], [9, 1]])
D = np.array([[2, 1, 1], [6, 8, 1], [2, 2, 6]])

print(la.det(C))
print(la.det(D))

-12.000000000000005
54.00000000000001


In [ ]:
# 12
print(la.inv(C))
print(la.inv(D))

[[-0.08333333  0.16666667]
 [ 0.75       -0.5       ]]
[[ 0.85185185 -0.07407407 -0.12962963]
 [-0.62962963  0.18518519  0.07407407]
 [-0.07407407 -0.03703704  0.18518519]]


In [ ]:
# 13
print(la.eig(C)[0])

[ 8.4244289 -1.4244289]


In [ ]:
# 14
# 2x + y = 9
# 7x + 3y = 41
li_X = np.array([[2, 1], [7, 3]])
li_Y = np.array([9, 41]).reshape(2, -1)

# 14-1
print(np.matmul(la.inv(li_X), li_Y))

# 14-2
print(np.linalg.solve(li_X, li_Y))

[[ 14.]
 [-19.]]
[[ 14.]
 [-19.]]


In [ ]:
# 15
from numpy.linalg import LinAlgError

def isSingularMatrix(m):
  print("인자로 들어온 행렬 = ")
  print(np.array(m))

  try:
    np.linalg.inv(m)
  except LinAlgError as e:
    print("특이행렬입니다.")
  else:
    print("특이행렬이 아닙니다.")
  print()

In [ ]:
# 15-1
isSingularMatrix([[0, 0], [0, 0]])

인자로 들어온 행렬 = 
[[0 0]
 [0 0]]
특이행렬입니다.



In [ ]:
# 15-2
isSingularMatrix(np.eye(4))

인자로 들어온 행렬 = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
특이행렬이 아닙니다.



In [ ]:
# 15-3
for i in range(5):
  isSingularMatrix(np.random.randn(3, 3))

인자로 들어온 행렬 = 
[[ 1.03855963  0.94743409 -0.0293222 ]
 [-0.56260128 -0.11335695 -0.55383533]
 [ 0.24750387 -0.0724073  -0.60458386]]
특이행렬이 아닙니다.

인자로 들어온 행렬 = 
[[-0.08911231  0.30325176 -0.50596735]
 [-1.27043107  0.87584433  0.03620236]
 [ 1.06534526  0.16372723 -1.35187034]]
특이행렬이 아닙니다.

인자로 들어온 행렬 = 
[[-0.08379286 -1.3402367  -0.49686311]
 [-1.20363494 -1.19225124  0.51464571]
 [-1.09794101 -0.74282857 -0.46451035]]
특이행렬이 아닙니다.

인자로 들어온 행렬 = 
[[ 0.82301896  0.54774821 -0.21796876]
 [-0.14698689  0.92579169  0.1548672 ]
 [ 0.03849351 -1.10523325 -0.95132297]]
특이행렬이 아닙니다.

인자로 들어온 행렬 = 
[[ 1.86202963  0.26798236 -0.58206437]
 [ 0.7143465   0.6986614  -1.07913542]
 [ 0.83057547  0.67869446 -1.84892834]]
특이행렬이 아닙니다.

